# -*- coding: utf-8 -*-
"""smartwatts_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12o_3LWZzPUD0kt5GU2hYb_zrjKaPv9hD
"""

#imports only
from google.cloud import bigquery
from google.colab import auth
from scipy.stats import pearsonr

from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense, Input, LSTM, GRU, Dropout,TimeDistributed
from keras.optimizers import SGD,Adam
from sklearn.metrics import mean_absolute_error, mean_squared_error

import math
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

auth.authenticate_user()
print("Authenticated!!")

project_id='smartwatts-project'

# Commented out IPython magic to ensure Python compatibility.
#displays interactive dataframes can be ignored.
# %load_ext google.colab.data_table
# %reload_ext google.colab.data_table
print("Reloaded")

# Commented out IPython magic to ensure Python compatibility.
# #magic typing specifically for bigquery it since we only use the client once to get the data from BQ. we also name the dataset as df
# %%bigquery df --project {project_id}
# SELECT
#   esiid, usage_hourly, usage_kwh,
#   temp_f, humidity, wind_speed_mph,
#   pressure_hpa, hour_of_day, day_of_week,
#   month, year, is_weekend
# FROM `smartwatts.mart`
# ORDER BY esiid, usage_hourly

#verification df is saved correctly
print(df.shape)
print(df.dtypes)
print(df.head())

#seperates each essid in their own dataframe
esiid_data={esiid: group.copy() for esiid, group in df.groupby('esiid')}

for esiid, data in esiid_data.items():
  print(f"ESIID: {esiid}")
  print(data.head())
  print(f"Row count {len(data)}")
  print("\n")

features = ['usage_kwh', 'temp_f', 'humidity',
            'wind_speed_mph', 'pressure_hpa', 'hour_of_day',
            'day_of_week', 'month', 'is_weekend']
correlation={}
for esiid, data in esiid_data.items():

  corr_matrix = data[features].corr()['usage_kwh'].drop('usage_kwh')
  correlation[esiid] = corr_matrix

  plt.figure(figsize=(10,8))
  sns.heatmap(corr_matrix.to_frame(), annot=True, cmap='coolwarm') # Reshape Series to DataFrame for heatmap
  plt.show()

"""Looking at the correlation matrix we can see that based on our output. Energy Usage per kilo watt shows there is evidence that temperature and hour of day have a strong correlation to energy usage."""

def create_sequences(data, input_seq_len, output_seq_len):
    X, y = [], []
    for i in range(len(data) - input_seq_len - output_seq_len + 1):
        X.append(data[i : i + input_seq_len])                          # all 3 features
        y.append(data[i + input_seq_len : i + input_seq_len + output_seq_len, 0])  # kwh only
    return np.array(X), np.array(y)

#sequences son
input_sequence_length=168
output_sequence_length=720
features = ['usage_kwh', 'temp_f', 'hour_of_day', 'day_of_week', 'month', 'is_weekend']
train={}
test={}
scalers = {}
prepared={}

for esiid, data in esiid_data.items():
  df = data[features].copy().reset_index(drop=True)

  train_len = math.ceil(len(df) * 0.8)
  train[esiid] = df[:train_len]
  test[esiid] = df[train_len:]

  scaler = MinMaxScaler(feature_range=(0,1))
  train_scaled = scaler.fit_transform(train[esiid].values)
  test_scaled = scaler.transform(test[esiid].values)

  scalers[esiid] = scaler

  x_train, y_train = create_sequences(train_scaled, input_sequence_length, output_sequence_length)
  x_test, y_test = create_sequences(test_scaled, input_sequence_length, output_sequence_length)
  prepared[esiid] = {
      'x_train': x_train,
      'y_train': y_train,
      'x_test': x_test,
      'y_test': y_test
  }
  print(f"ESIID: {esiid}")
  print(f"Train length: {len(train[esiid])}")
  print(f"Test length: {len(test[esiid])}")

all_train_raw_dfs = []
all_test_raw_dfs = []

for esiid in esiid_data.keys():
    # Append raw (unscaled) train and test dataframes for concatenation
    all_train_raw_dfs.append(train[esiid][features].copy())
    all_test_raw_dfs.append(test[esiid][features].copy())

# Concatenate all raw train and test dataframes
combined_train_df = pd.concat(all_train_raw_dfs, axis=0).reset_index(drop=True)
combined_test_df = pd.concat(all_test_raw_dfs, axis=0).reset_index(drop=True)

# Create and fit a single scaler for the combined 'general' dataset
general_scaler = MinMaxScaler(feature_range=(0,1))
combined_train_scaled = general_scaler.fit_transform(combined_train_df.values)
combined_test_scaled = general_scaler.transform(combined_test_df.values)

# Store the general scaler
scalers["general"] = general_scaler

# Create sequences for the 'general' model using the globally scaled data
x_train_general, y_train_general = create_sequences(combined_train_scaled, input_sequence_length, output_sequence_length)
x_test_general, y_test_general = create_sequences(combined_test_scaled, input_sequence_length, output_sequence_length)

prepared["general"] = {
    "x_train": x_train_general,
    "y_train": y_train_general,
    "x_test": x_test_general,
    "y_test": y_test_general
}

from keras.callbacks import EarlyStopping
from keras.regularizers import l2

#creating RNN Model
def train_RNN(esiid,prepared):
  x_train = prepared[esiid]['x_train']
  y_train = prepared[esiid]['y_train']
  x_test = prepared[esiid]['x_test']
  y_test = prepared[esiid]['y_test']


  model = Sequential([
      Input(shape=(input_sequence_length, x_train.shape[2])),
      SimpleRNN(units=64,
                return_sequences=True),
      Dropout(0.1),
      SimpleRNN(units=32,
                return_sequences=False),
      Dropout(0.1),
      Dense(output_sequence_length)
  ])
  model.summary()
  model.compile(optimizer=Adam(clipvalue=1.0), loss='mse')

  early_stop = EarlyStopping(monitor='val_loss',
                             patience=2,
                             restore_best_weights=True,
                             verbose=1)
  model.fit(
            x_train, y_train,
            epochs=15,
            batch_size=128,
            validation_data=(x_test, y_test),
            callbacks=[early_stop]
            )
  loss=model.evaluate(x_test, y_test)
  print(f"Test Loss: {loss}")

  return model

def train_LSTM(esiid,prepared):
  x_train = prepared[esiid]['x_train']
  y_train = prepared[esiid]['y_train']
  x_test = prepared[esiid]['x_test']
  y_test = prepared[esiid]['y_test']

  model = Sequential([
      Input(shape=(input_sequence_length, x_train.shape[2])),
      LSTM(50,
           return_sequences=True,
           input_shape=(x_train.shape[1],1),
           kernel_regularizer=l2(0.001),
           recurrent_regularizer=l2(0.001)),
      Dropout(0.1),
      LSTM(25,
           return_sequences=False,
           kernel_regularizer=l2(0.001),
           recurrent_regularizer=l2(0.001)),
      Dropout(0.1),
      Dense(output_sequence_length)
  ])

  model.summary()
  model.compile(optimizer=Adam(clipvalue=1.0), loss='mse')

  early_stop = EarlyStopping(monitor='val_loss',
                             patience=2,
                             restore_best_weights=True,
                             verbose=1)
  model.fit(
      x_train,
      y_train,
      validation_data=(x_test, y_test),
      epochs=15, batch_size=128,
      callbacks=[early_stop]
  )
  loss=model.evaluate(x_test, y_test)
  print(f"Test Loss: {loss}")
  return model

def train_GRU(esiid, prepared):
  x_train = prepared[esiid]['x_train']
  y_train = prepared[esiid]['y_train']
  x_test = prepared[esiid]['x_test']
  y_test = prepared[esiid]['y_test']

  model = Sequential([
      Input(shape = (input_sequence_length, x_train.shape[2])),
      GRU(units=50,
          return_sequences=True,
          kernel_regularizer=l2(0.001),
          recurrent_regularizer=l2(0.001)
      ),
      Dropout(0.1),
      GRU(units=25,
          return_sequences=False,
          kernel_regularizer=l2(0.001),
          recurrent_regularizer=l2(0.001)
      ),
      Dropout(0.1),
      Dense(output_sequence_length)
  ])
  model.summary()
  model.compile(optimizer=SGD(
                        learning_rate=0.01,
                        decay = 1e-7,
                        momentum=0.9,
                        nesterov=False),
                loss='mean_squared_error'
                )

  early_stop = EarlyStopping(monitor='val_loss',
                             patience=2,
                             restore_best_weights=True,
                             verbose=1)
  model.fit(x_train,
            y_train,
            validation_data=(x_test, y_test),
            epochs=15,
            batch_size=128,
            callbacks = [early_stop]
            )
  loss = model.evaluate(x_test, y_test)
  print(f"Test Loss: {loss}")
  return model

def predict(model, x_test, scaler):

  predictions_scaled = model.predict(x_test)

  num_features = scaler.n_features_in_
  arr_flat = predictions_scaled.reshape(-1)

  pad = np.zeros((len(arr_flat), num_features))
  pad[:, 0] = arr_flat

  predictions = scaler.inverse_transform(pad)[:,0]

  return predictions.reshape(predictions_scaled.shape)

RNN_model={}
LSTM_model={}
GRU_model={}

for esiid in esiid_data.keys():
  print(f"Training RNN Model for {esiid}")
  RNN_model[esiid] = train_RNN(esiid, prepared)

  print(f"Training LSTM Model for {esiid}")
  LSTM_model[esiid] = train_LSTM(esiid, prepared)

  print(f"Training GRU Model for {esiid}")
  GRU_model[esiid] = train_GRU(esiid, prepared)
  print(f"Finished Training {esiid}")
  print("\n")

print("Training General Model\nPlease Wait...")
print("[1/3] Training RNN")
RNN_model["general"] = train_RNN("general", prepared)

print("[2/3] Training LSTM")
LSTM_model["general"] = train_LSTM("general", prepared)

print("[3/3] Training GRU")
GRU_model["general"] = train_GRU("general", prepared)

print("Finished Training General Model")

def evaluate_model(model, esiid, prepared, scalers):
    x_test  = prepared[esiid]['x_test']
    y_test  = prepared[esiid]['y_test']
    scaler  = scalers[esiid]

    pred = model.predict(x_test, verbose=0)

    # squeeze out any extra dimensions first
    pred   = pred.squeeze()    # (samples, output_sequence_length)
    y_test = y_test.squeeze()  # ensure same shape

    # flatten to 1D
    pred_flat   = pred.reshape(-1, 1)
    actual_flat = y_test.reshape(-1, 1)

    # pad to `len(features)` cols for inverse transform, take col 0 (kwh)
    def inverse_kwh(arr):
        # The scaler was fitted on `len(features)` columns.
        # We need to pad the single kwh column to `len(features)` columns
        # for inverse transformation.
        num_features = len(features)
        padded = np.concatenate([arr, np.zeros((len(arr), num_features - 1))], axis=1)
        return scaler.inverse_transform(padded)[:, 0]

    pred_kwh   = inverse_kwh(pred_flat)
    actual_kwh = inverse_kwh(actual_flat)

    mape = np.mean(np.abs(
        (actual_kwh - pred_kwh) / np.where(actual_kwh == 0, 1, actual_kwh)
    )) * 100

    return {
        'mae':  mean_absolute_error(actual_kwh, pred_kwh),
        'mse':  np.sqrt(mean_squared_error(actual_kwh, pred_kwh)),
        'mape': mape
    }

metrics={}

for esiid in esiid_data.keys():
  metrics[esiid] = {
      'rnn':  evaluate_model(RNN_model[esiid],  esiid, prepared, scalers),
      'lstm': evaluate_model(LSTM_model[esiid], esiid, prepared, scalers),
      'gru':  evaluate_model(GRU_model[esiid],  esiid, prepared, scalers),
    }

for esiid, results in metrics.items():
  print(f"\n{esiid}")
  for model_name, result in results.items():
    print(f"{model_name}: {result}")

metrics["general"] = {
      'rnn':  evaluate_model(RNN_model["general"],  "general", prepared, scalers),
      'lstm': evaluate_model(LSTM_model["general"], "general", prepared, scalers),
      'gru':  evaluate_model(GRU_model["general"],  "general", prepared, scalers),
    }

print("General")
for model_name, results in metrics["general"].items():
  print(f"{model_name}: {results}")

best_models={}

for esiid in list(esiid_data.keys()) + ['general']:
    esiid_metrics=metrics[esiid]
    best_model_name = min(esiid_metrics, key=lambda x: esiid_metrics[x]['mae'])
    model_lookup = {"rnn": RNN_model, "lstm": LSTM_model, "gru": GRU_model}
    best_models[esiid] = {"model": model_lookup[best_model_name][esiid],
                          "model_type": best_model_name
                          }
    print(f"{esiid} best model: {best_model_name} MAE: {esiid_metrics[best_model_name]['mae']}")
  #

RNN_prediction = {}
LSTM_prediction = {}
GRU_prediction={}

"""
Add code for saving models to GCS.
Add code to upload general model, and Each ESIID Model.
Upload each model by their esiid and model name.
> Add blockquote

"""

for esiid, model in LSTM_model.items():
  print(f"Esiid: {esiid} , Model Name: {model}")

#upload general model to gcs
gcs_path = f"gs://smartwatts-models-final/models"
for esiid, model in RNN_model.items():
  print(f"saving {model}")
  model.save(f"{gcs_path}/RNN/{esiid}.keras")
for esiid, model in LSTM_model.items():
  print(f"saving {model}")
  model.save(f"{gcs_path}/LSTM/{esiid}.keras")
for esiid, model in GRU_model.items():
  print(f"saving {model}")
  model.save(f"{gcs_path}/GRU/{esiid}.keras")

all_metrics=[]
predictions = {
    "rnn": RNN_prediction,
    "lstm": LSTM_prediction,
    "gru": GRU_prediction
}

models={
    "rnn": RNN_model,
    "lstm": LSTM_model,
    "gru": GRU_model
}
client = bigquery.Client(project="smartwatts-project")

def upload_dataset_to_BQ(df, table_name):
  job=client.load_table_from_dataframe(df,table_name)
  job.result()

for model_name, model_dict in models.items():
    for esiid in model_dict.keys():
        print(f"saving metrics for {esiid}")
        all_metrics.append({
            "run_date": pd.Timestamp.utcnow(),
            "model_type": model_name.upper(),
            "esiid": esiid,
            "mae": metrics[esiid][model_name]["mae"],
            "mse": metrics[esiid][model_name]["mse"],
            "mape": metrics[esiid][model_name]["mape"],
            "input_hours": input_sequence_length,
            "output_hours": output_sequence_length,
        })
metrics_df = pd.DataFrame(all_metrics)

all_predictions = []

for esiid, best in best_models.items():
    pred = predict(
        model=best["model"],
        x_test=prepared[esiid]["x_test"],
        scaler=scalers[esiid]
    )
    pred_flat = pred[0]
    start_time = pd.Timestamp.utcnow().floor('h')
    timestamps = pd.date_range(start=start_time, periods=len(pred_flat), freq='h')

    all_predictions.append(pd.DataFrame({
        "prediction_time": timestamps,
        "model_type": best["model_type"].upper(),
        "esiid": esiid,
        "predicted_kwh": pred_flat
    }))

predictions_df = pd.concat(all_predictions)

"""Only run predict on whole dataset to verify we are running normally. Once Completed we find the best model to predict on."""

dataset_id = "smartwatts-project.forecasting"
dataset=bigquery.Dataset(dataset_id)
dataset.location="US"

client.create_dataset(dataset,timeout=30,exists_ok=True)
print("Created dataset {}.{}".format(client.project, dataset.dataset_id))

upload_dataset_to_BQ(metrics_df, "smartwatts-project.forecasting.model_metrics")
print("Finished uploading metrics\nUploading predictions")
upload_dataset_to_BQ(predictions_df, "smartwatts-project.forecasting.model_predictions")
print("Finished uploading Predictions")